### ISSUE TITLE
Sluggish performance in gvcf2DB rule

### ISSUE THREAD

**Issue by ChabbyTMD** [harvardinformatics/snpArcher#239]
Each instance of this rule takes about 3-4 days to complete. I specified the interval variant calling approach and the recommended thread count of 1 for the gvcf2DB rule in the profile config. 

```YAML
 bam2gvcf: 2 # Should be run with no more than 2 threads.
 concat_gvcfs: 1 # Does NOT use more than 1 thread.
 bcftools_norm: 1 # Does NOT use more than 1 thread.
 create_db_mapfile: 1 # Does NOT use more than 1 thread.
 gvcf2DB: 1 # Should be run with no more than 2 threads.
```

The log file would seem to suggest as well that snakemake might be experiencing a scheduling issue once a collection of gvcf2DB jobs is done executing. It will hang on the message below for about 2-3 days before executing another round of jobs. 

```
Failed to solve scheduling problem with ILP solver in time (10s). Falling back to greedy solver.
```

I would appreciate some insight into the issue and would be more than happy to provide further detail.
