### ISSUE TITLE
<TBD> Percolating into resources

### ISSUE THREAD

**Issue by brantfaircloth** [harvardinformatics/snpArcher#245]
This may be an offshoot of #240, and I think that it's coming from snakemake (e.g. [tbdstring.py](https://github.com/snakemake/snakemake/blob/44b953602ac27690aedb545390a59a75a436c68a/src/snakemake/common/tbdstring.py#L1)), but it seems that `<TBD>` is sometimes being set as the `tmpdir`, even when a `tmpdir` is provided in `config.yaml` (e.g. as `bigtmp`).  I haven't quite figured out how or why this is happening, but it causes some commands to fail, as in calls to create the gvcf (truncated for clarity and some file names changed):
```
bcftools concat -D -a -Ou results/xxxxx/[various files] 2> logs/xxx/concat_gvcfs/logfile.txt | bcftools sort -T <TBD> -Oz -o results/xxxxx/gvcfs/final.g.vcf.gz - 2>> logs/xxxxxx/concat_gvcfs/<individual>.txt

tabix -p vcf results/xxxxx/gvcfs/final.g.vcf.gz 2>> logs/xxxxxx/concat_gvcfs/<individual>.txt
```
I'm playing around with some different ways of avoiding the error but wanted to put it on your radar.  It has not been a problem using earlier versions of snakemake/snpArcher.

**Comment by cademirch** [comment]
Thanks for the report. What version of Snakemake and what does your config file and or profile look like?

**Comment by brantfaircloth** [comment]
Hi Cade,

I'm dumb - I just found a typo in the `config.yaml` for the `bigtmp` parameter - that seems to be the issue - running now and keeping an eye on GVCF creation.

What makes this a little tricky is that the failure does not seem to generate any logging info (e.g. the log file for this step of the process for a given sample is empty) and it's a  bit of a mystery why `<TBD>` gets substituted if `bigtmp` is incorrectly specified.

```
snakemake --version
9.3.2
```
`config.yaml` looks like:
```yaml
##############################
# Variables you need to change
##############################

samples: "config/samples.csv" # path to the sample metadata CSV
final_prefix: "RAW" # prefix for final output files
intervals: True #Set to True if you want to perform variant calling using interval approach.
sentieon: False #set to True if you want to use sentieon, False if you want GATK
sentieon_lic: "" #set to path of sentieon license
remote_reads: False # Set True if reads are in a location seperate from --default-remote-prefix.
remote_reads_prefix: "" # set to google bucket prefix where reads live. FOR SNAKEMAKE 7.X.X ONLY.
bigtmp: "/var/scratch" #Set to a path with lots of free space to use for commands that require large amounts of temp space; defaults to system tmpdir if empty
cov_filter: True #set to True if you want to include coverage thresholds in the callable sites bed file (default uses mappability only)
generate_trackhub: False #Set to true if you want to generate a Genome Browser Trackhub. Dependent on postprocessing module.
trackhub_email: ""
mark_duplicates: True
sort_reads: False
```
and profile currently looks like the following. I recently explicitly added the `tmpdir` to the slurm profile hoping I could force things to behave better (and before noticing the error in my `config.yaml`.
```yaml
executor: slurm
use-conda: True
jobs: 40 # Have up to N jobs submitted at any given time
latency-wait: 100 # Wait N seconds for output files due to latency
retries: 2 # Retry jobs N times.

# These resources will be applied to all rules. Can be overriden on a per-rule basis below.
default-resources:
  mem_mb: 'attempt * 4000'
  mem_mb_reduced: '(attempt * 4000) * 0.9' # Mem allocated to java for GATK rules (tries to prevent OOM errors)
  slurm_partition: 'single'
  slurm_account: 'hpc_bfstart_10' # Same as sbatch -A. Not all clusters use this.
  runtime: '720' # In minutes
  tmpdir: '/var/scratch'

set-resources:
  bam2gvcf: # HaplotypeCaller
    mem_mb: 'attempt * 8000'
    mem_mb_reduced: '(attempt * 8000) * 0.9' # Mem allocated to java (tries to prevent OOM errors)
    slurm_partition: 'single'
    slurm_account: 'hpc_bfstart_10' # Same as sbatch -A. Not all clusters use this.
    runtime: '2160'
    cpus_per_task: '2'
    tmpdir: '/var/scratch'
```
